// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: token_store.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenValueRequest) Reset() {
	*x = TokenValueRequest{}
	mi := &file_token_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenValueRequest) ProtoMessage() {}

func (x *TokenValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenValueRequest.ProtoReflect.Descriptor instead.
func (*TokenValueRequest) Descriptor() ([]byte, []int) {
	return file_token_store_proto_rawDescGZIP(), []int{0}
}

func (x *TokenValueRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenValueRequest) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TokenValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenValueResponse) Reset() {
	*x = TokenValueResponse{}
	mi := &file_token_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenValueResponse) ProtoMessage() {}

func (x *TokenValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenValueResponse.ProtoReflect.Descriptor instead.
func (*TokenValueResponse) Descriptor() ([]byte, []int) {
	return file_token_store_proto_rawDescGZIP(), []int{1}
}

func (x *TokenValueResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_token_store_proto protoreflect.FileDescriptor

const file_token_store_proto_rawDesc = "" +
	"\n" +
	"\x11token_store.proto\x12\x05proto\"E\n" +
	"\x11TokenValueRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\fR\bmetadata\"*\n" +
	"\x12TokenValueResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value2J\n" +
	"\n" +
	"TokenStore\x12<\n" +
	"\x05Value\x12\x18.proto.TokenValueRequest\x1a\x19.proto.TokenValueResponseB\tZ\a./protob\x06proto3"

var (
	file_token_store_proto_rawDescOnce sync.Once
	file_token_store_proto_rawDescData []byte
)

func file_token_store_proto_rawDescGZIP() []byte {
	file_token_store_proto_rawDescOnce.Do(func() {
		file_token_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_token_store_proto_rawDesc), len(file_token_store_proto_rawDesc)))
	})
	return file_token_store_proto_rawDescData
}

var file_token_store_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_token_store_proto_goTypes = []any{
	(*TokenValueRequest)(nil),  // 0: proto.TokenValueRequest
	(*TokenValueResponse)(nil), // 1: proto.TokenValueResponse
}
var file_token_store_proto_depIdxs = []int32{
	0, // 0: proto.TokenStore.Value:input_type -> proto.TokenValueRequest
	1, // 1: proto.TokenStore.Value:output_type -> proto.TokenValueResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_token_store_proto_init() }
func file_token_store_proto_init() {
	if File_token_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_token_store_proto_rawDesc), len(file_token_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_token_store_proto_goTypes,
		DependencyIndexes: file_token_store_proto_depIdxs,
		MessageInfos:      file_token_store_proto_msgTypes,
	}.Build()
	File_token_store_proto = out.File
	file_token_store_proto_goTypes = nil
	file_token_store_proto_depIdxs = nil
}
