// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: token_store.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TokenStore_Value_FullMethodName = "/proto.TokenStore/Value"
)

// TokenStoreClient is the client API for TokenStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenStoreClient interface {
	Value(ctx context.Context, in *TokenValueRequest, opts ...grpc.CallOption) (*TokenValueResponse, error)
}

type tokenStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenStoreClient(cc grpc.ClientConnInterface) TokenStoreClient {
	return &tokenStoreClient{cc}
}

func (c *tokenStoreClient) Value(ctx context.Context, in *TokenValueRequest, opts ...grpc.CallOption) (*TokenValueResponse, error) {
	out := new(TokenValueResponse)
	err := c.cc.Invoke(ctx, TokenStore_Value_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenStoreServer is the server API for TokenStore service.
// All implementations should embed UnimplementedTokenStoreServer
// for forward compatibility
type TokenStoreServer interface {
	Value(context.Context, *TokenValueRequest) (*TokenValueResponse, error)
}

// UnimplementedTokenStoreServer should be embedded to have forward compatible implementations.
type UnimplementedTokenStoreServer struct {
}

func (UnimplementedTokenStoreServer) Value(context.Context, *TokenValueRequest) (*TokenValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Value not implemented")
}

// UnsafeTokenStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenStoreServer will
// result in compilation errors.
type UnsafeTokenStoreServer interface {
	mustEmbedUnimplementedTokenStoreServer()
}

func RegisterTokenStoreServer(s grpc.ServiceRegistrar, srv TokenStoreServer) {
	s.RegisterService(&TokenStore_ServiceDesc, srv)
}

func _TokenStore_Value_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenStoreServer).Value(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenStore_Value_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenStoreServer).Value(ctx, req.(*TokenValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenStore_ServiceDesc is the grpc.ServiceDesc for TokenStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TokenStore",
	HandlerType: (*TokenStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Value",
			Handler:    _TokenStore_Value_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "token_store.proto",
}
